/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Trivia;

import resources.LocalizationUtil;

/**
 *
 * @author Yosef
 */
public class ChoseLanguage extends javax.swing.JFrame {

    /**
     * Creates new form ChoseLanguage
     */
    private static String lan;
    public ChoseLanguage() {
        initComponents();
        this.setSize(400,300);
        SelectWantLan.setText(LocalizationUtil.localizedResourceBundle.getString("SelectWantdLan"));
        btnHeb.setText(LocalizationUtil.localizedResourceBundle.getString("heb"));
        btnEnglish.setText(LocalizationUtil.localizedResourceBundle.getString("en"));
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnHeb = new javax.swing.JButton();
        btnEnglish = new javax.swing.JButton();
        SelectWantLan = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(200, 300));
        getContentPane().setLayout(null);

        btnHeb.setText("Hebrew");
        btnHeb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHebActionPerformed(evt);
            }
        });
        getContentPane().add(btnHeb);
        btnHeb.setBounds(212, 131, 143, 67);

        btnEnglish.setText("English");
        btnEnglish.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnglishActionPerformed(evt);
            }
        });
        getContentPane().add(btnEnglish);
        btnEnglish.setBounds(51, 131, 143, 67);

        SelectWantLan.setFont(new java.awt.Font("Maiandra GD", 1, 14)); // NOI18N
        SelectWantLan.setText("          Select Wanted Language");
        getContentPane().add(SelectWantLan);
        SelectWantLan.setBounds(67, 29, 274, 72);

        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(jPanel1);
        jPanel1.setBounds(20, 10, 370, 100);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEnglishActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnglishActionPerformed
       this.lan="en";
       this.dispose();
    }//GEN-LAST:event_btnEnglishActionPerformed

    private void btnHebActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHebActionPerformed
        this.lan="iw";
        this.dispose();
    }//GEN-LAST:event_btnHebActionPerformed

    public String getLanguche(){
        return lan;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChoseLanguage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChoseLanguage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChoseLanguage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChoseLanguage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ChoseLanguage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel SelectWantLan;
    private javax.swing.JButton btnEnglish;
    private javax.swing.JButton btnHeb;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
