/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Trivia;

import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.SwingConstants;
import resources.LocalizationUtil;

/**
 *
 * @author Yosef
 */
public class OpenScreen extends javax.swing.JFrame {
    static User current;
    static String userName;
    
    /**
     * Creates new form OpenScreen
     */
    public OpenScreen(User currentUser) {
        initComponents();
        this.setSize(650,350);
        this.current=currentUser;
       int biuldComboBox=DataBaseMange.getInstance().countQues();
       for(int i=0;i<biuldComboBox;i++)
       this.cmbQuesNum.addItem(i+1); //set the real number of question from db
       this.setTitle(LocalizationUtil.localizedResourceBundle.getString("WelcomGame"));
       LogOutBtn.setText(LocalizationUtil.localizedResourceBundle.getString("LogOutKey"));
       PleaseChoseCntQues.setText(LocalizationUtil.localizedResourceBundle.getString("PleaseChoseCntQues"));
       PleaseChoseCntQues.setHorizontalAlignment(SwingConstants.CENTER);
       btnStartGame.setText(LocalizationUtil.localizedResourceBundle.getString("StartGameKey"));
       btnShowHighScoreTble.setText(LocalizationUtil.localizedResourceBundle.getString("HighScoreTble"));
      
       if(Integer.parseInt(current.getHighstScore(current))> 20){
           ShowCrownIcon();
       }
       else if(Integer.parseInt(current.getHighstScore(current))> 15){
           ShowKnightIcon();
       }
       else if(Integer.parseInt(current.getHighstScore(current))> 10){
           ShowDragonIcon();
       }
       setBackGround();
        setLocationRelativeTo(null);
      OpenTitelWitName.setText(LocalizationUtil.localizedResourceBundle.getString("WelcomGame")+" "+current.getUserName());
      OpenTitelWitName.setHorizontalAlignment(SwingConstants.CENTER);
      currebtPlayerHighScore.setText((LocalizationUtil.localizedResourceBundle.getString("BestScore"))+" "+current.getHighstScore(current));
      currebtPlayerHighScore.setHorizontalAlignment(SwingConstants.CENTER);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnStartGame = new javax.swing.JButton();
        PleaseChoseCntQues = new javax.swing.JLabel();
        cmbQuesNum = new javax.swing.JComboBox();
        btnShowHighScoreTble = new javax.swing.JButton();
        OpenTitelWitName = new javax.swing.JLabel();
        currebtPlayerHighScore = new javax.swing.JLabel();
        LogOutBtn = new javax.swing.JButton();
        CrownImg = new javax.swing.JLabel();
        BackgroudTrivia = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Welcome To Trivia Game");
        setForeground(java.awt.Color.white);
        setIconImages(null);
        getContentPane().setLayout(null);

        btnStartGame.setText("Ok");
        btnStartGame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStartGameActionPerformed(evt);
            }
        });
        getContentPane().add(btnStartGame);
        btnStartGame.setBounds(250, 220, 150, 30);

        PleaseChoseCntQues.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        PleaseChoseCntQues.setText("Please chose how much ques you want");
        getContentPane().add(PleaseChoseCntQues);
        PleaseChoseCntQues.setBounds(150, 110, 350, 40);

        cmbQuesNum.setModel(cmbQuesNum.getModel());
        cmbQuesNum.setToolTipText("");
        cmbQuesNum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbQuesNumActionPerformed(evt);
            }
        });
        getContentPane().add(cmbQuesNum);
        cmbQuesNum.setBounds(300, 170, 45, 20);

        btnShowHighScoreTble.setText("Table of records");
        btnShowHighScoreTble.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShowHighScoreTbleActionPerformed(evt);
            }
        });
        getContentPane().add(btnShowHighScoreTble);
        btnShowHighScoreTble.setBounds(260, 270, 130, 30);

        OpenTitelWitName.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        getContentPane().add(OpenTitelWitName);
        OpenTitelWitName.setBounds(140, 20, 360, 40);

        currebtPlayerHighScore.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        getContentPane().add(currebtPlayerHighScore);
        currebtPlayerHighScore.setBounds(130, 70, 360, 30);

        LogOutBtn.setText("Log Out");
        LogOutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogOutBtnActionPerformed(evt);
            }
        });
        getContentPane().add(LogOutBtn);
        LogOutBtn.setBounds(531, 10, 100, 30);
        getContentPane().add(CrownImg);
        CrownImg.setBounds(20, 10, 0, 90);
        getContentPane().add(BackgroudTrivia);
        BackgroudTrivia.setBounds(0, 0, 650, 320);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnStartGameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStartGameActionPerformed
        int numQues=1;  //choose the real number of wanted ques
       numQues+=cmbQuesNum.getSelectedIndex();
       current.setLevel(0);
       current.setPoints(0);
       current.setWrongAnsCnt(0);
        System.out.println("selecetd numofques "+numQues);
        try {
            Game newGame=new Game(numQues,current,true); 
        } catch (Exception ex) {
            ex.printStackTrace(); //print all the hisory
        }
       this.dispose(); //close the window       

    }//GEN-LAST:event_btnStartGameActionPerformed

 public void setBackGround(){
       BackgroudTrivia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Trivia/Images/OpenScreenIcon.jpg"))); 
       getContentPane().add(BackgroudTrivia);
       BackgroudTrivia.setBounds(0, 0, 650, 320);
 }
    public void  ShowCrownIcon(){
//        JLabel CrownImage1=new JLabel(new ImageIcon("/Trivia/Images/Crown.png"));
//        this.getContentPane().add(CrownImage1);
//        CrownImage1.setBounds(20, 10, 90, 90);
        CrownImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Trivia/Images/Crown.png")));
        getContentPane().add(CrownImg);
        CrownImg.setBounds(20, 10, 90, 90);       
      }
    public void  ShowDragonIcon(){
//        JLabel CrownImage1=new JLabel(new ImageIcon("/Trivia/Images/Crown.png"));
//        this.getContentPane().add(CrownImage1);
//        CrownImage1.setBounds(20, 10, 90, 90);
        CrownImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Trivia/Images/Dragon.png")));
        getContentPane().add(CrownImg);
        CrownImg.setBounds(20, 10, 90, 90);       
      }
    public void  ShowKnightIcon(){
//        JLabel CrownImage1=new JLabel(new ImageIcon("/Trivia/Images/Crown.png"));
//        this.getContentPane().add(CrownImage1);
//        CrownImage1.setBounds(20, 10, 90, 90);
        CrownImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Trivia/Images/Knight.png")));
        getContentPane().add(CrownImg);
        CrownImg.setBounds(20, 10, 90, 90);       
      }
    
    private void cmbQuesNumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbQuesNumActionPerformed

   
    }//GEN-LAST:event_cmbQuesNumActionPerformed

    private void btnShowHighScoreTbleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShowHighScoreTbleActionPerformed
       
        HighstRecords highScore=new HighstRecords();
        
        highScore.setVisible(true);        
        
    }//GEN-LAST:event_btnShowHighScoreTbleActionPerformed

    private void LogOutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogOutBtnActionPerformed
        this.dispose();
        LogIn loGin=new LogIn();
        loGin.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_LogOutBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
         
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OpenScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OpenScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OpenScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OpenScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OpenScreen(current).setVisible(true);
            }
        });
    }

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BackgroudTrivia;
    private javax.swing.JLabel CrownImg;
    private javax.swing.JButton LogOutBtn;
    public javax.swing.JLabel OpenTitelWitName;
    private javax.swing.JLabel PleaseChoseCntQues;
    private javax.swing.JButton btnShowHighScoreTble;
    private javax.swing.JButton btnStartGame;
    public static javax.swing.JComboBox cmbQuesNum;
    private javax.swing.JLabel currebtPlayerHighScore;
    // End of variables declaration//GEN-END:variables
}
