/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Trivia;

import java.awt.Toolkit;
import java.io.DataInputStream;
import java.io.File;
import java.io.IOException;
import java.io.PrintStream;
import java.net.Socket;
import java.net.UnknownHostException;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileFilter;
import javax.swing.filechooser.FileNameExtensionFilter;
import resources.LocalizationUtil;

/**
 *
 * @author lidor
 */
public class SelectGame1 extends javax.swing.JFrame {

    PlaySounds bacgroundSound;
    static User current;
    DataInputStream input = null;
    Socket clientSocket = null;
    MusicClass Mp3ClassPlayer = new MusicClass();
    public static int count=1;
    int xMouse;
    int yMouse;
    static boolean firstTime=false;
    static boolean soundPlaying=false;
    
    int width = (Toolkit.getDefaultToolkit().getScreenSize().width / 2) - 185;
    int height = Toolkit.getDefaultToolkit().getScreenSize().height - 180;

    /**
     * Creates new form SelectGame1
     */
    public SelectGame1(User curentPlayer) {
        initComponents();
        this.current = curentPlayer;
        this.setSize(660, 345);
        setLocationRelativeTo(null);
        if(!firstTime){
            loadDefultSound();
            firstTime=true;
            soundPlaying=true;
        }
        title.setText(current.getUserName());
        //bacgroundSound = new PlaySounds("C:\\Users\\Yosef\\Documents\\NetBeansProjects\\Java\\TriviaGame1\\src\\Trivia\\Sounds\\ChillingMusic.wav");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LogOutBtn = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        title = new javax.swing.JLabel();
        chooseFile = new javax.swing.JLabel();
        pause = new javax.swing.JLabel();
        play = new javax.swing.JLabel();
        stop = new javax.swing.JLabel();
        loopPlay = new javax.swing.JLabel();
        background = new javax.swing.JLabel();
        javax.swing.JLabel jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        LogOutBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Trivia/Images/logout.png"))); // NOI18N
        LogOutBtn.setContentAreaFilled(false);
        LogOutBtn.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        LogOutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogOutBtnActionPerformed(evt);
            }
        });
        getContentPane().add(LogOutBtn);
        LogOutBtn.setBounds(570, 240, 70, 70);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Trivia/Images/1vs1n.png"))); // NOI18N
        jButton1.setContentAreaFilled(false);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(270, 110, 200, 70);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Trivia/Images/Singleplayer_Button.png"))); // NOI18N
        jButton2.setContentAreaFilled(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(250, 180, 240, 60);

        jLabel2.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel2.setText("Select game");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(300, 50, 150, 50);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Trivia/Images/headgears1.gif"))); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(-10, 0, 370, 400);
        getContentPane().add(title);
        title.setBounds(210, 10, 260, 30);

        chooseFile.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                chooseFileMouseReleased(evt);
            }
        });
        getContentPane().add(chooseFile);
        chooseFile.setBounds(620, 14, 20, 50);

        pause.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                pauseMouseReleased(evt);
            }
        });
        getContentPane().add(pause);
        pause.setBounds(580, 14, 30, 50);

        play.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                playMouseReleased(evt);
            }
        });
        getContentPane().add(play);
        play.setBounds(540, 14, 30, 60);

        stop.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                stopMouseReleased(evt);
            }
        });
        getContentPane().add(stop);
        stop.setBounds(500, 10, 30, 60);

        loopPlay.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                loopPlayMouseReleased(evt);
            }
        });
        getContentPane().add(loopPlay);
        loopPlay.setBounds(470, 10, 20, 60);

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Trivia/Images/BackgroundPlayer.png"))); // NOI18N
        background.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                backgroundMousePressed(evt);
            }
        });
        background.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                backgroundMouseDragged(evt);
            }
        });
        getContentPane().add(background);
        background.setBounds(470, 0, 190, 60);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Trivia/Images/OpenScreenIcon22.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 650, 320);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void loadDefultSound(){
        Mp3ClassPlayer.Stop();
        Mp3ClassPlayer.Play("C:\\Users\\Yosef\\Documents\\NetBeansProjects\\Java\\TriviaGame1\\src\\Trivia\\Sounds\\ChillingMusic.mp3"+"");
    }
    
    private void LogOutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogOutBtnActionPerformed
        this.dispose();
        LogIn loGin = new LogIn();
        loGin.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_LogOutBtnActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Mp3ClassPlayer.Stop();
        firstTime=false;
        Thread t = new Thread() {
            public void run() {
                try {
                    clientSocket = new Socket("localhost", 2222);
                    input = new DataInputStream(clientSocket.getInputStream());
                    PrintStream output = new PrintStream(clientSocket.getOutputStream());
                    //Scanner userInput = new Scanner(System.in);	
                    //output.println();

                } catch (UnknownHostException e) {
                    e.printStackTrace();
                } catch (IOException e) {
                    e.printStackTrace();
                }
                while (true) {
                    try {
                        if (input.readLine().equals("Statrt playe")) {
                            Thread t2 = new Thread(){
                                      public void run() {
                            try {
                                Game game = new Game(2, current, true, 1);
                               
                            } catch (Exception ex) {
                                Logger.getLogger(SelectGame1.class.getName()).log(Level.SEVERE, null, ex);
                            }
                        }
                            };
                            t2.start();
                             break;
                    }//else
                       // JOptionPane.showMessageDialog(SelectGame1.this, "Watting for another player");

                    } catch (IOException ex) {
                        Logger.getLogger(SelectGame1.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
            }
        };
        t.start();


    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Mp3ClassPlayer.Stop();
        firstTime=false;
        OpenScreen newGame = new OpenScreen(current);
        newGame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void backgroundMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backgroundMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        
        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_backgroundMouseDragged

    private void backgroundMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backgroundMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_backgroundMousePressed

    private void stopMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_stopMouseReleased
        soundPlaying=false;  
        Mp3ClassPlayer.Stop();    }//GEN-LAST:event_stopMouseReleased

    private void playMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_playMouseReleased
       if(!soundPlaying){
        Mp3ClassPlayer.Resume();
        soundPlaying=true;
       }
       
    }//GEN-LAST:event_playMouseReleased

    private void pauseMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pauseMouseReleased
       try {
            // TODO add your handling code here:
            Mp3ClassPlayer.Pause();
             soundPlaying=false;  
        } catch (IOException ex) {
            Logger.getLogger(SelectGame1.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_pauseMouseReleased

    private void chooseFileMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_chooseFileMouseReleased
        FileFilter filter = new FileNameExtensionFilter("MP3 Files", "mp3", "mpeg3");
        
        JFileChooser chooser = new JFileChooser("C:\\Music");
        chooser.addChoosableFileFilter(filter);
        
        int returnVal = chooser.showOpenDialog(null);
        
        if(returnVal == JFileChooser.APPROVE_OPTION){
            Mp3ClassPlayer.Stop();
            File myFile = chooser.getSelectedFile();
            String song = myFile + "";
          
            Mp3ClassPlayer.Play(song);
            
            
        }
    }//GEN-LAST:event_chooseFileMouseReleased

    private void loopPlayMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loopPlayMouseReleased
         switch(count){
            case 0:
                count = 1;
                break;
                
            case 1:
                count = 0;
                break;
            
        }
    }//GEN-LAST:event_loopPlayMouseReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SelectGame1.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SelectGame1.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SelectGame1.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SelectGame1.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SelectGame1(current).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton LogOutBtn;
    private javax.swing.JLabel background;
    private javax.swing.JLabel chooseFile;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel loopPlay;
    private javax.swing.JLabel pause;
    private javax.swing.JLabel play;
    private javax.swing.JLabel stop;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables
}
