/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Trivia;

import com.sun.awt.AWTUtilities;
import java.awt.BorderLayout;
import java.net.MalformedURLException;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JWindow;

/**
 *
 * @author lidor
 */
public class WaitingForUser extends javax.swing.JFrame {

    /**
     * Creates new form WaitingForUser
     */
    public WaitingForUser() {
        initComponents();
        
      
        
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(550, 380));
        setMinimumSize(new java.awt.Dimension(550, 380));
        setPreferredSize(new java.awt.Dimension(550, 380));
        getContentPane().setLayout(null);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Trivia/Images/loading.gif"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(30, 100, 410, 220);

        jLabel3.setText("wait You have finished the first Waiting for the other player");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(107, 11, 367, 55);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
public static void main(String[] args) throws MalformedURLException {

        
    ImageIcon icon = new ImageIcon("C:\\Users\\Yosef\\Documents\\NetBeansProjects\\Java\\TriviaGame1\\src\\Trivia\\Images\\LoadingWait.gif");
    JLabel label=new JLabel(icon);
    JWindow myJFrame=new JWindow();
    myJFrame.setLayout(new BorderLayout());
    myJFrame.add(label,BorderLayout.CENTER);
    myJFrame.setLocationRelativeTo(null);
    myJFrame.setOpacity(0.5f);
    myJFrame.setAlwaysOnTop(true);
    label.setOpaque(false);
    AWTUtilities.setWindowOpaque(myJFrame, false);
    myJFrame.pack();
    myJFrame.setVisible(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
